#!/usr/bin/env python3
import asyncio
from cgitb import text
from xml.etree.ElementTree import tostring

from requests import request
from tcp import Servidor
import re

def validar_nome(nome):
    return re.match(br'^[a-zA-Z][a-zA-Z0-9_-]*$', nome) is not None

def sair(conexao):
    
    temp_list = []
    for canal in conexao.canais:
        servidor.channels[canal].pop(conexao.nickid, None)
        for chave in servidor.channels[canal]:
            temp_list.append(servidor.channels[canal][chave])
    temp_list = list(dict.fromkeys(temp_list))
    for item in temp_list: # Envia sinal QUIT
            item.enviar(b':' + conexao.nickid + b' QUIT :Connection closed\r\n')
    
    if conexao.nickid != b'*':
        servidor.apelido_conexoes.pop(conexao.nickid) # remove a pessoa que esta saindo da conexão
    
    print(conexao, 'conexão fechada')
    conexao.fechar()


def dados_recebidos(conexao, dados):
    dados = conexao.dados_residuais + dados
    conexao.dados_residuais = b''

    if dados == b'':
        return sair(conexao) 

    if not dados.endswith(b'\r\n'):
        dados = list(filter((b'').__ne__, dados.split(b'\r\n')))
        conexao.dados_residuais += dados.pop()
    
    else:
        dados = list(filter((b'').__ne__, dados.split(b'\r\n')))  

    if dados:
        for message in dados:
            print(str(message))
            request, text = message.split(b' ', 1)

            if request == b'PING':
                conexao.enviar(b':server PONG server :' + text + b'\r\n')

            if request == b'NICK':
                if validar_nome(text):
                    if text.lower() in servidor.apelido_conexoes: #verificando se o nick ja  esta na lista do server
                        conexao.enviar(b':server 433 ' + conexao.nickid + b' ' + text + b' :Nickname is already in use\r\n')
                    elif conexao.nickid == b'*': 
                            conexao.enviar(b':server 001 ' + text + b' :Welcome\r\n' + b':server 422 ' + text + b' :MOTD File is missing\r\n')
                            servidor.apelido_conexoes[text.lower()] = conexao #adicionando a conexao nova ao dicionario da forma nick:conexao
                            conexao.nickid = text
                    else: 
                            conexao.enviar(b':' + conexao.nickid + b' NICK ' + text + b'\r\n')
                            servidor.apelido_conexoes.pop(conexao.nickid.lower()) # como iremos atualizar o nick, precisamos remover o antigo de nossa lista
                            servidor.apelido_conexoes[text.lower()] = conexao
                            conexao.nickid = text             
                else:
                    conexao.enviar(b':server 432 ' + conexao.nickid + b' ' + text + b' :Erroneous nickname\r\n') 
            
            if request == b'PRIVMSG':
                addressee, msg = text.split(b' ', 1)
                if addressee.startswith(b'#'):
                    if addressee.lower() in servidor.channels:
                        for key in servidor.channels[addressee.lower()]:
                            if servidor.channels[addressee.lower()][key] != conexao:
                                servidor.channels[addressee.lower()][key].enviar(b':' + conexao.nickid + b' PRIVMSG ' + addressee + b' ' + msg + b'\r\n')
                elif addressee.lower() in servidor.apelido_conexoes:
                    servidor.apelido_conexoes[addressee.lower()].enviar(b':' + conexao.nickid + b' PRIVMSG ' + addressee + b' ' + msg + b'\r\n')
            
            if request == b'JOIN':
                if text.startswith(b'#') and validar_nome(text[1:]):
                    if text.lower() not in servidor.channels:
                        servidor.channels[text.lower()] = {}
                    servidor.channels[text.lower()][conexao.nickid.lower()] = conexao

                    if text.lower() not in conexao.canais:
                        conexao.canais.append(text.lower())
                    membros = b''

                    for key in servidor.channels[text.lower()]:
                        servidor.channels[text.lower()][key].enviar(b':' + conexao.nickid + b' JOIN :' + text + b'\r\n')

                    for key in sorted(servidor.channels[text.lower()].keys()): 
                        membros += key + b' '
                    send = b':server 353 ' + conexao.nickid + b' = ' + text + b' :' + membros #Enviando mensagem com os nicks de membros do canal
                    conexao.enviar(send + b'\r\n' + b':server 366 ' + conexao.nickid + b' ' + text + b' :End of /NAMES list.\r\n')
                else:
                    conexao.enviar(b':server 403 ' + text + b' :No such channel.\r\n') #Mensagem de erro caso o canal não exista

            if request == b'PART':
                text = text.split(b' ')[0]
                for user in servidor.channels[text]:
                    servidor.apelido_conexoes[user].enviar(b':' + conexao.nickid + b' PART ' + text + b'\r\n')
                del servidor.channels[text.lower()][conexao.nickid]

                    
    print(conexao, dados)


def conexao_aceita(conexao):
    print(conexao, 'nova conexão')
    conexao.nickid = b'*'
    conexao.dados_residuais = b''
    conexao.canais = []
    conexao.registrar_recebedor(dados_recebidos)

servidor = Servidor(6667)
servidor.apelido_conexoes = {}
servidor.channels = {}

servidor.registrar_monitor_de_conexoes_aceitas(conexao_aceita)
asyncio.get_event_loop().run_forever()
